docker run -ti --rm \
-e DISPLAY \
-v /tmp/.X11-unix:/tmp/.X11-unix:ro \
-v $HOME/.Xauthority:/home/developer/.Xauthority:ro \
--device /dev/snd:/dev/snd \
--device /dev/dri/card0:/dev/dri/card0 \
-v /run/user/$UID/pulse/native:/home/developer/pulse/socket:ro \
-v $HOME/Programs/goland:/home/developer/goland \
-v $HOME/Workspace:/home/developer/Workspace \
-v $HOME/Workspace/go:/home/developer/go \
--net=host --pid=host --ipc=host goland 
